### ISSUE TITLE
Using letters (A, B, C, etc) instead of KEY_A as enums for KeyboardKey is not a great idea

### ISSUE THREAD

**Issue by Tuatarian** [greenfork/nimraylib_now#10]
I know it's not within Nim's style to use capital letters to store variable information,, but I think this naming convention is just bound to cause problems, and it's not notably better than raylib's use of KEY_A

**Comment by greenfork** [comment]
You can take a look at readme https://github.com/greenfork/nimraylib_now#enums
So you can use either `A` when compiler can guess what it is or you can use `KeyboardKey.A` to fully qualify this enum. You can always use the second option if you prefer.

Does that answer your concerns?

**Comment by Tuatarian** [comment]
I still think this is not optimal, purely because KeyboardKey.A is much wordier than the regular KEY_A

**Comment by greenfork** [comment]
I agree that there's a trade-off. I thought that it would be more concise to write just `A` and use namespace only when required, e.g. when you have a constant. Let me know if you have a strong use case against it, we can reconsider

**Comment by Tuatarian** [comment]
There isn't a particularly compelling reason to do either way I think, ultimately both will work fine. As the repo owner it's your judgement here
