### ISSUE TITLE
not prefixing rlgl functions with rl is a really bad idea

### ISSUE THREAD

**Issue by Tuatarian** [greenfork/nimraylib_now#11]
rlEnd() (a very very vital function) simply doesn't exist because end is a keyword in nim. Please return back to using the rl prefix

**Comment by greenfork** [comment]
You can use functions (and everything else) which are reserved words like this:
```
`end`()
```

But I recommend using namespaces to deal with rlgl module specifically. You can read more about it here https://github.com/greenfork/nimraylib_now#require-fully-qualified-procs

**Comment by Tuatarian** [comment]
using from rl import nil is probably a good idea, very good point

**Comment by greenfork** [comment]
General idea is that you _can_ use it without namespace but you are in control of how you want to do it
