### ISSUE TITLE
Text doesn't show up on crown.nim example

### ISSUE THREAD

**Issue by RationalG** [greenfork/nimraylib_now#3]
Nim version is 1.4.2
Raylib version is 3.5.0
Linux distro : Pop!_OS 20.04 LTS x86_64

After compiling and launching the crown.nim example, I noticed the text drawing doesn't seem to work on my side. "Press Space to pause" and "I AM NIM" doesn't show up anywhere on the screen.
All the rest is drawn and displayed perfectly on screen.
![crown](https://user-images.githubusercontent.com/1936748/105125317-1fd62480-5aaa-11eb-9f00-996763140888.png)

```
INFO: Initializing raylib 3.5
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 3440 x 1440
INFO:     > Render size:  800 x 600
INFO:     > Screen size:  800 x 600
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: OpenGL 3.3 Core profile supported
INFO: GL: OpenGL device information:
INFO:     > Vendor:   NVIDIA Corporation
INFO:     > Renderer: GeForce RTX 2060/PCIe/SSE2
INFO:     > Version:  3.3.0 NVIDIA 455.38
INFO:     > GLSL:     3.30 NVIDIA via Cg compiler
INFO: GL: Supported extensions count: 395
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: GL: Anisotropic textures filtering supported (max: 16X)
INFO: GL: Mirror clamp wrap texture mode supported
INFO: TEXTURE: [ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Compiled successfully
INFO: SHADER: [ID 2] Compiled successfully
INFO: SHADER: [ID 3] Program loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Internal vertex buffers initialized successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully
INFO: RLGL: Default state initialized successfully
INFO: TEXTURE: [ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: FONT: Default font loaded successfully
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
INFO: TEXTURE: [ID 1] Unloaded default texture data from VRAM (GPU)
INFO: Window closed successfully
```

EDIT : i also tried to compile one of the text examples (text_format_text.nim), still doesn't work.

**Comment by greenfork** [comment]
Hi! That is strange, maybe there are some problems with fonts. Could you please try these things:
- Try to run [textures_image_text.nim](https://github.com/greenfork/nimraylib_now/blob/master/examples/textures/textures_image_text.nim) example which loads a custom font
- Try to compile and run original [text_format_text.c](https://github.com/raysan5/raylib/blob/a0a840101c499d19f9b455916a231123a0cd8e45/examples/text/text_format_text.c) example: 
```shell
$ gcc -lraylib -lm text_format_text.c
$ ./a.out
```

**Comment by greenfork** [comment]
Another check: insert `echo getFontDefault()` somewhere in the program, for example after `initWindow` call and see if it outputs something in the console. For me it outputs this:

(baseSize: 10, charsCount: 224, charsPadding: 0, texture: (id: 2, width: 128, height: 128, mipmaps: 1, format: 2), recs: ..., chars: ...)

**Comment by RationalG** [comment]
Thank you greenfork, I will come back later in the day once I tried your suggestions.

**Comment by greenfork** [comment]
Sure, no rush!

**Comment by RationalG** [comment]
texture_image_text.nim succeed to load the font and the image but nothing shows up on the screen.

gcc is not able to compile text_format_text.c and display this error : 
```
/usr/bin/ld: /tmp/ccdy2nvD.o: in function `main':
text_format_text.c:(.text+0x2d): undefined reference to `InitWindow'
/usr/bin/ld: text_format_text.c:(.text+0x4c): undefined reference to `SetTargetFPS'
/usr/bin/ld: text_format_text.c:(.text+0x56): undefined reference to `BeginDrawing'
/usr/bin/ld: text_format_text.c:(.text+0x7d): undefined reference to `ClearBackground'
/usr/bin/ld: text_format_text.c:(.text+0xb6): undefined reference to `TextFormat'
/usr/bin/ld: text_format_text.c:(.text+0xd1): undefined reference to `DrawText'
/usr/bin/ld: text_format_text.c:(.text+0x10a): undefined reference to `TextFormat'
/usr/bin/ld: text_format_text.c:(.text+0x125): undefined reference to `DrawText'
/usr/bin/ld: text_format_text.c:(.text+0x15e): undefined reference to `TextFormat'
/usr/bin/ld: text_format_text.c:(.text+0x179): undefined reference to `DrawText'
/usr/bin/ld: text_format_text.c:(.text+0x19c): undefined reference to `GetFrameTime'
/usr/bin/ld: text_format_text.c:(.text+0x1bd): undefined reference to `TextFormat'
/usr/bin/ld: text_format_text.c:(.text+0x1d8): undefined reference to `DrawText'
/usr/bin/ld: text_format_text.c:(.text+0x1dd): undefined reference to `EndDrawing'
/usr/bin/ld: text_format_text.c:(.text+0x1e2): undefined reference to `WindowShouldClose'
/usr/bin/ld: text_format_text.c:(.text+0x1f2): undefined reference to `CloseWindow'
collect2: error: ld returned 1 exit status
```

I am not sure why it doesn't find the references, since raylib.h is in /usr/local/include.

As for `getDefaultFont()`, it displays the following : 
`(baseSize: 0, charsCount: 0, charsPadding: 0, texture: (id: 0, width: 0, height: 0, mipmaps: 0, format: 0), recs: ..., chars: ...)`

This is a problem I guess.

**Comment by greenfork** [comment]
`text_format_text.c:(.text+0x2d): undefined reference to InitWindow` this and similar errors usually happen when there's no `-lraylib` flag for `gcc`. Could you also include the command you used to compile the file?

You said that `raylib.h` is in `/usr/local/include`, does it mean you installed the library manually, not using your package manager? From what I see Pop_OS uses Ubuntu's package manager and it should have raylib.

Let's try to compile the C file to narrow the issue down a little bit more. Assuming your `raylib.h` is in `/usr/local/include` and `libraylib.so` is in `/usr/local/lib`:
```shell
$ gcc -L/usr/local/lib -lraylib -lm -I/usr/local/include text_format_text.c
$ ./a.out
```

If you have any problems figuring out where the library files are located you can do the following, which should output all the paths for `.h` files:
```shell
$ gcc -M text_format_text.c
```

**Comment by RationalG** [comment]
Yes I did a manual install for raylib. `raylib.h` is in `/usr/local/include` while **libraylib.so** is in **/usr/local/lib** indeed.

I used the exact same commands you gave me in your previous posts to compile the file. Unfortunately, the -lraylib flag doesn't resolve the problem on my side. I have the exact same errors : `undefined reference to "X"`

**Comment by RationalG** [comment]
By the way, raylib haven't shipped their package to Ubuntu packages repository yet. I was forced to build it and install it manually.

**Comment by greenfork** [comment]
Could you try to download prebuilt binaries for the library from raylib's release page as described in the readme? https://github.com/greenfork/nimraylib_now#linux

This seems to be the problem with raylib library installation

**Comment by RationalG** [comment]
It's finally working ! 
Installing the prebuilt binaries have resolved the problem.
`librarylib.so` has to be moved inside `/usr/local/lib`, but more importantly `libraylib.so.350` has to be located inside /lib otherwise the program will complaint : `error while loading shared libraries: libraylib.so.350: cannot open shared object file: No such file or directory`

Now the examples are working. Thank you very much greenfork

**Comment by greenfork** [comment]
You are welcome, have fun building games!
