### ISSUE TITLE
How to add CMAKE options of raylib to control features?

### ISSUE THREAD

**Issue by AllenDang** [greenfork/nimraylib_now#37]
Say if I want to enable SUPPORT_BUSY_WAIT_LOOP, where should I put it?

I read the HACK manual and tried following changes

```
allowIfs = [ 
  "SUPPORT_BUSY_WAIT_LOOP",
  "RAYGUI_SUPPORT_ICONS"  
]
```

And ran 

```sh
nimble convert
```
But it seems the flags doesn't work. Am i doing something wrong?

**Comment by greenfork** [comment]
These are flags that must be passed to C compiler, in Nim this can be done via `--passC` option, docs https://nim-lang.org/docs/nimc.html

`RAYGUI_SUPPORT_ICONS` is also defined to provide additional functions and nimraylib_now library already accounts for it and adds necessary bindings.

`SUPPORT_BUSY_WAIT_LOOP` this only defines additional runtime behavior and does not provide any additional functions, so nimraylib_now library doesn't need to know about it.

I suppose that everything should work fine if you compile your nim program like so:
```
nim c --passC:"-DSUPPORT_BUSY_WAIT_LOOP -DRAYGUI_SUPPORT_ICONS" --gc:orc file.nim
```

**Comment by AllenDang** [comment]
@greenfork Thanks very much! It works.
