### ISSUE TITLE
Loading Custom Font

### ISSUE THREAD

**Issue by wwderw** [greenfork/nimraylib_now#43]
I was wondering if there is a way to load a different font that would be bundled with the binary?

I saw in one example here about getting the system default font, but this wouldn't be a default font.

I tried using the example in the C++ raylib examples using loadFontEx, but either my conversion to the nim syntax version isn't correct or I am missing something.

Or if there is another way of getting a custom font loaded into the program.

Thanks for the help.

**Comment by greenfork** [comment]
Hi! Do any of these examples help?

https://github.com/greenfork/nimraylib_now/blob/468105fdd9d5539eac6fe3c5ca8f01d7fd7234f5/examples/textures/textures_image_text.nim#L24

https://github.com/greenfork/nimraylib_now/blob/468105fdd9d5539eac6fe3c5ca8f01d7fd7234f5/examples/textures/textures_image_drawing.nim#L44

**Comment by wwderw** [comment]
Both throw the same error "conversion from Font to itself is pointless".  Which is different from what I was getting the first go round as well.

The first one is more applicable, as I am doing a TTF file.  Although the first time I was doing it, I was following from the raylib example, so it did look like I was doing it wrong the first go round as well.

**Comment by greenfork** [comment]
How exactly do you get the error "conversion from Font to itself is pointless"? Is this the literal error message?
Do you use development version of Nim or custom-built Raylib library? Anything non-standard?

**Comment by wwderw** [comment]
It's an error thru VSCodium using the Nim extension.

I'm running the official release raylib binary for Linux.  Official Nim 1.4.8 release.

**Comment by wwderw** [comment]
The example worked and I was able to get what I needed to get it to work for my project from my project.  I hadn't looked in the textures folders and their examples.

Thanks for the help!!!

**Comment by greenfork** [comment]
Sure, I'm glad it worked out for you!
