### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by wwderw** [greenfork/nimraylib_now#44]
Same source works fine on Linux, but when building using Mingw with the latest official Raylib using Windows 8.1, I get "Assertion failed: window != NULL".  Using the mingw from the nim website as well as the official latest Nim as well.

It points to window.c line 516 in the "raylib_mangled/external/glfw/src/window.c"

I don't know if it has something to do with my src or not as it compiles fine under Linux.  Thoughts?

**Comment by greenfork** [comment]
Do I understand correctly that you are cross-compiling from Linux to Windows? Cross-compiling works best when you don't cross-compile and instead use a container with Windows OS. There were some threads on the Nim forum about doing it as a GitHub CI action. Maybe it's also possible to do it via Docker container. I didn't explore cross-compiling too much.

**Comment by greenfork** [comment]
"latest official Raylib" - what do you mean by that exactly? Raylib sources are bundled together with this library. Do you use dynamic linking on Windows? https://github.com/greenfork/nimraylib_now/blob/master/USING_RAYLIB.md

**Comment by wwderw** [comment]
No, I have my own dedicated Windows box that I use for compilation on Windows.  I setup the exact some tooling that I have on Linux on my Windows box.

As far as latest goes, in the Release section of the Raylib github, I grab the latest .exe that the project has compiled themselves and install that on my computer.  The compiler for Nim, I grab that off the Nim website below the Nim lang download itself (I don't use the finish binary with Nim to do that).

If I recall correctly, static linking is done by default with the "official" binaries of Raylib that they have in their release section.  However, that error is also on the Windows box that has done compilation, so even if it was dynamic linking, if linking was an issue, I don't think it would have shown up on that computer, but I could be wrong about that.

**Comment by greenfork** [comment]
Okay, thanks!

> Raylib github, I grab the latest .exe

Nim comes with its own MinGW compiler so when you use .exe, there could be a conflict with different MinGW compilers. I would try to uninstall that unless you know what you are doing.

> It points to window.c line 516 in the "raylib_mangled/external/glfw/src/window.c"

Judging by this error, you are using the code which is supplied with this library NimraylibNow!, so you don't need to download anything.

> It points to window.c line 516 in the "raylib_mangled/external/glfw/src/window.c"

https://github.com/greenfork/nimraylib_now/blob/617532f123a123e666aeecc39211c079210d9e4a/src/csources/raylib_mangled/external/glfw/src/window.c#L516

This line points to a function which sets a window's icon. Do you set the icon for your window somehow? If not, then it just probably means that the window fails to initialize, and it is a very basic problem. Maybe there's a compiler flag that you must supply for Windows 8.1, I'm not sure here.

So your options are:
1. Use dynamic linking as described in [the document](https://github.com/greenfork/nimraylib_now/blob/master/USING_RAYLIB.md). You would need to download a compiled with MinGW library like this one `raylib-3.7.0_win64_mingw-w64.zip` and unarchive it in the same directory as your game .exe file.
2. Current CI runs on latest Windows, so I assume that it definitely works on Windows 10. You could try doing the compilation via a docker container.
3. Else you will have to debug it somehow.

**Comment by wwderw** [comment]
I actually do set the icon on my window.

I load the image with loadImage() and then I use setWindowIcon().  After I initWindow().

The mingw that comes with the raylib exe does not get set on PATH during install, so I thought I was safe there as far as compilers getting in the way.  Was that incorrect?

**Comment by greenfork** [comment]
You could try without the icon. Or use the function to set the icon later in the code, maybe the order is a bit different on Windows for some reason.

> The mingw that comes with the raylib exe does not get set on PATH during install, so I thought I was safe there as far as compilers getting in the way. Was that incorrect?

I have no experience developing on Windows so I can't tell for sure if there are no caveats but logically it seems correct.

**Comment by wwderw** [comment]
It appears that  setting icon needs to be after I setTargetFPS() when I setWindowIcon().   Or atleast that was the first spot that seemed logical to try, without getting into the loop.

Worse comes to worse, without the icon worked as well, setting the icon is just one of those finishing touches that I like to have if able.

Thanks for the help!

**Comment by greenfork** [comment]
You are welcome, happy to help!
