### ISSUE TITLE
Using nimraylib_now with staticly linked library (opengl2.1)

### ISSUE THREAD

**Issue by ayko-chan** [greenfork/nimraylib_now#58]
Hi,i have a older pc that dosent support opengl3, how do i make that the static lib is compiled with the 2.1 version of opengl?

**Comment by greenfork** [comment]
Hi! You could pass a `#define` option to C compiler.

https://github.com/raysan5/raylib/blob/423fdb320a5acaa9f2b853598825de40068087e2/src/rlgl.h#L24-L31

In your case you would pass `--passC:"-DGRAPHICS_API_OPENGL_21"` option to `nim`.
