### ISSUE TITLE
[Suggestion] rename vector math operations to the mathematical symbols

### ISSUE THREAD

**Issue by RecruitMain707** [greenfork/nimraylib_now#6]
Such as `VectorXAdd` -> `+`

**Comment by greenfork** [comment]
We have this: https://github.com/greenfork/nimraylib_now#raymath-infix-operators

Implemented here: https://github.com/greenfork/nimraylib_now/blob/master/src/nimraylib_now/raymath.nim#L475

Let me know if I'm missing something. So far I did it for simple arithmetic operations `+-*/`

**Comment by RecruitMain707** [comment]
sorry, im dumb :P
