### ISSUE TITLE
[Help needed] I want to run the executable file I created as a standalone program.

### ISSUE THREAD

**Issue by nnahito** [greenfork/nimraylib_now#61]
Thank you for the best program.

I would like to create a game using nimraylib_now.
I have written one code, with a sample.

I used the following command to create the executable.
```
nim c --gc:orc -d:release -r stg.nim
```

I was using Windows, so an exe file was created.
Then I sent the exe file to my friend.
However, an error message "The application was unable to start correctly (0x00000007b)" is displayed.

How do I distribute a finished game to end users?
Is there a way to distribute it including MinGW?

I would appreciate it if you could tell me.
Thank you very much.

**Comment by greenfork** [comment]
Hi, thanks! Unfortunately I don't know how to do this on Windows. But the question is not specific to NimraylibNow, you can ask a general question, "how to make a standalone executable" and use the answer for your game as well.

There are several places you can ask/search for an answer:
- Nim forum https://forum.nim-lang.org/
- Nim discord https://discord.gg/zg2vvAPf
- And other ways, you can see them under "Community" header https://nim-lang.org/

Hope you will get it fixed!
