### ISSUE TITLE
cmake support

### ISSUE THREAD

**Issue by locriacyber** [greenfork/nimraylib_now#70]
While using nimraylib_now, I discovered that `setMouseCursor` doesn't work.

I tried writing the same program in C using `raylib` from system package manager (which uses `glfw` from package manager). It works.

**Comment by greenfork** [comment]
Hi, @locriacyber ! Could you clarify what exactly you are trying to achieve and why do you think cmake will help you?

**Comment by locriacyber** [comment]
@greenfork wow you replied fast. I was still writing the issue description.

**Comment by greenfork** [comment]
Could you share an example? If I can reproduce it, I can fix it

**Comment by locriacyber** [comment]
I suspect this is because of raylib's vendored glfw is not the newest.
```nim
import nimraylib_now

initWindow(800,800, "hi")
setMouseCursor(MouseCursor.IBEAM)
while not windowShouldClose():
  beginDrawing()
  endDrawing()
```

**Comment by locriacyber** [comment]
Yeah, the vendored glfw has the issue.

**Comment by locriacyber** [comment]
I think I found the problem. nimraylib_now does not link with X11, so GLFW just uses the dummy window backend.

**Comment by greenfork** [comment]
@locriacyber your example works for me fine. I see the cursor as IBEAM
