### ISSUE TITLE
Value with a raylib type is not copied during object copy

### ISSUE THREAD

**Issue by arnaudchenyensu** [greenfork/nimraylib_now#80]
Not sure if it's a bug with nimraylib_now or Nim (or my own understanding) but this piece of code is not behaving correctly:

```nim
import nimraylib_now

type
  ContainerKind = enum row, column
  Container = object
    kind: ContainerKind
    pos: Vector2
    elements: seq[Rectangle]
    width: int
    height: int
    margin: int
    spacing: int

proc changePos(container: Container): Container =
  var res = container
  res.pos.x = 200
  # correctly displays (x: 200.0, y: 0.0)
  echo "inside function: ", res.pos
  return res

var a = Container()
var b = a.changePos()

# both display (x: 0.0, y: 0.0)
echo "a: ", a.pos
echo "b: ", b.pos
```

I expect `b.pos.x` to be equal to 200 but it is actually equal to 0. However, if you remove some properties from type Container, `b.pos.x` become equals to 200:

```nim
import nimraylib_now

type
  Container = object
    pos: Vector2

proc changePos(container: Container): Container =
  var res = container
  res.pos.x = 200
  # correctly displays (x: 200.0, y: 0.0)
  echo "inside function: ", res.pos
  return res

var a = Container()
var b = a.changePos()

# display (x: 0.0, y: 0.0)
echo "a: ", a.pos
# display (x: 200.0, y: 0.0)
echo "b: ", b.pos
```

I'm using Nim Compiler Version 1.6.6 [MacOSX: arm64], NimraylibNow! v0.14 and Raylib v4.0.

**Comment by greenfork** [comment]
Thanks for reproducible examples and versions!

This looks like a bug in the Nim compiler that might never be fixed. Nim v2 is going to the direction of an "orc" memory management system. With orc both examples output correct values, could you try running your scripts with:
```
nim --mm:orc file.nim
```

Also note that `--mm:orc` is the recommended way to compile programs with the NimraylibNow library

**Comment by arnaudchenyensu** [comment]
Thank you for your quick answer, it's working!
