### ISSUE TITLE
NixOS: GLFW: Error: 65542 Description: GLX: Failed to load GLX

### ISSUE THREAD

**Issue by auroraanna** [greenfork/nimraylib_now#84]
No window comes up when I try to run my program (which uses nimraylib_now of couse). I get this error:
```console
> nimble run          
  Verifying dependencies for snekim@0.1.0
      Info: Dependency on nimraylib_now@any version already satisfied
  Verifying dependencies for nimraylib_now@0.15.0
      Info: Dependency on regex@any version already satisfied
  Verifying dependencies for regex@0.19.0
      Info: Dependency on unicodedb@>= 0.7.2 already satisfied
  Verifying dependencies for unicodedb@0.10.0
   Building snekim/snekim using c backend
INFO: Initializing raylib 4.2
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
WARNING: GLFW: Error: 65542 Description: GLX: Failed to load GLX
WARNING: GLFW: Failed to initialize Window
FATAL: Failed to initialize Graphic Device
```
[We already checked in the raylib discord that it's not a fault of my hardware or drivers](https://discord.com/channels/426912293134270465/427518168995725317/1025168200004018216).

**Comment by greenfork** [comment]
Hey, thanks for the link to your discussion! What is the exact command executed when you run `nimble run`?

This is the first time I see this error and it could be connected to NixOS. If you would like to tweak your build options, you can discover your package path with `nimble path nimraylib_now` and there the file [nimraylib_now/static_build.nim](https://github.com/greenfork/nimraylib_now/blob/master/src/nimraylib_now/static_build.nim) is like a "Makefile". You can also inspect the exact commands used to build raylib with `nim --listCmd ...` so that you have a full view of all the paths used to C compiler etc.

**Comment by auroraanna** [comment]
The command compiles and run my project consisting of `snekim.nimle`:
```nimble

**Comment by greenfork** [comment]
Unfortunately I don't think I can help with just the information I have right now. There are some debugging techniques I have listed above that would help you to figure out the correct path to resolve it.

You can still use NimraylibNow! bindings with a dynamic library `.so`, see [here](https://github.com/greenfork/nimraylib_now/blob/master/USING_RAYLIB.md) for details. Using a system-provided Raylib library is the easiest option. By default I try to statically compile all the C code which produces some strange issues on NixOS for some reason.

**Comment by auroraanna** [comment]
Figured it out! Running the binary works with `steam-run`.

**Comment by auroraanna** [comment]
`steam-run` should only be needed for development too since the error should go away when a nixpkg is created for my game.

**Comment by greenfork** [comment]
Okay, great to know! I'm not familiar with this `steam-run` so I wonder if this is going to be useful to other people as well, maybe I should put it into a troubleshooting section?

**Comment by auroraanna** [comment]
Would be useful to NixOS users I guess tho they might also find this issue when they get the same error.

**Comment by auroraanna** [comment]
Not sure :woman_shrugging: `steam-run` is kind of general knowledge on NixOS.

**Comment by greenfork** [comment]
Added to the troubleshooting section. If this "general knowledge" was not the first thing you tried to do, I guess it is not obvious enough so we better include it for future people to not stumble upon this issue and make them search for the answer.

**Comment by auroraanna** [comment]
So, steam-run runs something in an FHS environment which NixOS does not have by default.

**Comment by auroraanna** [comment]
> Unfortunately I don't think I can help with just the information I have right now. There are some debugging techniques I have listed above that would help you to figure out the correct path to resolve it.
> 
> You can still use NimraylibNow! bindings with a dynamic library `.so`, see [here](https://github.com/greenfork/nimraylib_now/blob/master/USING_RAYLIB.md) for details. Using a system-provided Raylib library is the easiest option. By default I try to statically compile all the C code which produces some strange issues on NixOS for some reason.

Huh, dunno why I didn't listen to you and try shared library… it works now with raylib installed and `nimble build -d:nimraylib_now_shared`.

**Comment by auroraanna** [comment]
Maybe you could add a note to the troubleshooting that you should use shared library on NixOS?

**Comment by greenfork** [comment]
Great, thanks! Added.
