### ISSUE TITLE
Compiled app doesn't start.

### ISSUE THREAD

**Issue by TTSKarlsson** [greenfork/nimraylib_now#93]
OS: Windows 11

Maybe I'm missing a step but the compiled crown.nim app doesn't start.

![image](https://user-images.githubusercontent.com/9962943/226195635-54b87fa7-7e41-4538-8e48-912bf9944a42.png)

. There are no compile errors, the main.nim contains the raw copy of crown.nim with no changes.
. If I start from explorer I get a failure and it tries to open a cmd prompt, which fails in terminal.

![image](https://user-images.githubusercontent.com/9962943/226195903-0691c23f-a193-4d23-b8c7-98f54e47eeea.png)

**Comment by greenfork** [comment]
Would [this troubleshooting section](https://github.com/greenfork/nimraylib_now#windows-error-the-application-was-unable-to-start-correctly-0x00000007b) help?

**Comment by TTSKarlsson** [comment]
Adding `--passL:-static` for static compilation worked! Thanks a lot mate!

**Comment by greenfork** [comment]
Great, glad it helped!
